[package]
name = "json-pragmatic"
version = "1.11.3"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "An examples for solving rich VRP"
publish = false

[dependencies]
vrp-pragmatic = { path = "../../vrp-pragmatic", version = "1.11.3" }

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "general_benchmark"
harness = false
