[package]
name = "vrp-pragmatic"
version = "1.18.4"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2021"
description = "An extension logic for solving rich VRP"

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.18.4" }

serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"

time = { version = "0.3.15", features = ["parsing", "formatting"] }
rand = { version = "0.8.5", features = ["small_rng"] }
hashbrown = "0.12.3"

[dev-dependencies]
proptest = "1.0.0"
uuid = { version = "1.1.2", features = ["v4"] }
