[package]
name = "vrp-core"
version = "1.2.3"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "A core algorithms to solve a Vehicle Routing Problem"

[dependencies]
rayon = "1.3.0"
rand = "0.7.3"
hashbrown = "0.7.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
js-sys = "0.3.37"
