[package]
name = "vrp-core"
version = "1.15.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2021"
description = "A core algorithms to solve a Vehicle Routing Problem"

[dependencies]
rosomaxa = { path = "../rosomaxa", version = "0.1.0" }

rayon = "1.5.1"
rand = "0.8.5"
hashbrown = "0.12.0"
