name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build and run tests
      run: cargo test --verbose

    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-features --tests -- -D warnings

  release-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Release build
      run: cargo build --release --verbose

  wasm-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build WebAssembly
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        cd vrp-cli
        wasm-pack build --target web

    - name: Upload WebAssembly artifact
      uses: actions/upload-artifact@v2
      with:
        name: vrp_cli_wasm
        path: vrp-cli/pkg/