name: Experiment with configs

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'An experiment job name (collect-metrics or bench-scientific)'
        required: true

      config_url:
        description: 'An experiment config url'
        required: true

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'collect-metrics' }}
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      -  run: python ./examples/experiments/collect-metrics.py ${{ github.event.inputs.config_url }}

      - name: Upload Results artifact
        uses: actions/upload-artifact@v2
        with:
          name: experiments-results.csv
          path: examples/experiments/collect-metrics-results.csv


  bench-scientific:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'bench-scientific' }}
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: python ./examples/experiments/bench-scientific.py ${{ github.event.inputs.config_url }}

      - name: Upload Results artifact
        uses: actions/upload-artifact@v2
        with:
          name: bench-results
          path: examples/experiments/results

